settings:
  start_date: "2018-01-01"
  base_currency: "EUR"

forex:
  symbols: "USD,RON,GBP"

macro_indicators:
  - series_id: "CP0000EZ19M086NEST"
    name: "eurozone_inflation"
    country: "EU"
    params: { frequency: "m", units: "pc1" }
  - series_id: "ECBDFR"
    name: "ecb_rate"
    country: "EU"
    params: { frequency: "d" }
  - series_id: "IRLTLT01DEM156N"
    name: "germany_10y_bond"
    country: "Germany"
    params: { frequency: "m" }
  - series_id: "IRLTLT01ITM156N"
    name: "italy_10y_bond"
    country: "Italy"
    params: { frequency: "m" }
  - series_id: "CP0000ROM086NEST"
    name: "romania_inflation"
    country: "Romania"
    params: { frequency: "m", units: "pc1" }
  - series_id: "IRLTLT01ROM156N"
    name: "romania_10y_bond"
    country: "Romania"
    params: { frequency: "m" }
  - series_id: "IRLTLT01GBM156N"
    name: "uk_10y_bond"
    country: "UK"
    params: { frequency: "m" }

equities:
  - symbol: "EWG"
    name: "Germany_ETF"
    country: "Germany"
    macro_region: "EU"
    currency: "USD"
    type: "etf"
  - symbol: "EWQ"
    name: "France_ETF"
    country: "France"
    macro_region: "EU"
    currency: "USD"
    type: "etf"
  - symbol: "EWI"
    name: "Italy_ETF"
    country: "Italy"
    macro_region: "EU"
    currency: "USD"
    type: "etf"
  - symbol: "EWU"
    name: "UK_ETF"
    country: "UK"
    macro_region: "UK"
    currency: "USD"
    type: "etf"